from .cambio import CambioProvider
from .cantamen import CantamenIXSIProvider
from .deer import Deer
from .example import ExampleProvider
from .fleetster import FleetsterAPI
from .flinkster import FlinksterProvider
from .lastenvelo_fr import LastenVeloFreiburgProvider
from .moqo import MoqoProvider
from .noi import NoiProvider
from .voi_raumobil import VoiRaumobil
